# ------------------------------------------------------------------------------
# Linstor-controller is main control point for Linstor, it provides API for
# clients and communicates with satellites for creating and monitor DRBD-devices
# ------------------------------------------------------------------------------

controller:
  enabled: true
  image:
    repository: kvaps/linstor-controller
    tag: v1.7.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  port: 3370
  ssl:
    enabled: true
    port: 3371

  # nodeSelector:
  #   node-role.kubernetes.io/master: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule
  
  initSettings:
    enabled: false
    # Set plain connector listen to localhost 
    plainConnectorBindAddress: "127.0.0.1"
    # Disable user security (required for setting global options)
    disableUserSecurity: true

  # Database config
  db:
    user: linstor
    password: linstor
    connectionUrl: jdbc:h2:/data/linstordb

  # PostgreSQL example
  # db:
  #   user: linstor
  #   password: linstor
  #   connectionUrl: jdbc:postgresql://linstor-db-stolon-proxy/linstor


# ------------------------------------------------------------------------------
# Stunnel is used to encrypt all the connections between linstor-controller and
# linstor-clients
# ------------------------------------------------------------------------------

stunnel:
  enabled: true
  image:
    repository: kvaps/linstor-stunnel
    tag: v1.7.0
    pullPolicy: IfNotPresent

# ------------------------------------------------------------------------------
# Linstor-satellites run on every node, they listen and perform controller tasks
# They operates directly with LVM and ZFS subsystems
# ------------------------------------------------------------------------------

satellite:
  enabled: true
  image:
    repository: kvaps/linstor-satellite
    tag: v1.7.0
    pullPolicy: IfNotPresent
    pullSecrets:
      - name: regsecret

  ssl:
    enabled: true

  # Oerwrite drbd.conf and global_common.conf files. This option will enable
  # usage-count=no and udev-always-use-vnr options by default
  overwriteDrbdConf: true

  # How many nodes can simultaneously download new image
  update:
    maxUnavailable: 40

  # nodeSelector:
  #   linstor-satellite: ""
  
  # tolerations:
  #   - key: node-role.kubernetes.io/master
  #     operator: Exists
  #     effect: NoSchedule

# ------------------------------------------------------------------------------
# Linstor CSI driver provides compatibility level for adding Linstor support
# for Kubernetes
# ------------------------------------------------------------------------------

csi:
  enabled: true
  image:
    pullSecrets:
      - name: regsecret
    linstorCsiPlugin:
      repository: docker.io/kvaps/linstor-csi
      tag: resize
      pullPolicy: IfNotPresent
    csiProvisioner:
      repository: quay.io/k8scsi/csi-provisioner
      tag: v1.5.0
      pullPolicy: IfNotPresent
    csiAttacher:
      repository: quay.io/k8scsi/csi-attacher
      tag: v2.1.1
      pullPolicy: IfNotPresent
    csiResizer:
      repository: quay.io/k8scsi/csi-resizer
      tag: v0.5.0
      pullPolicy: IfNotPresent
    csiSnapshotter:
      repository: quay.io/k8scsi/csi-snapshotter
      tag: v2.0.1
      pullPolicy: IfNotPresent
    csiNodeDriverRegistrar:
      repository: quay.io/k8scsi/csi-node-driver-registrar
      tag: v1.2.0
      pullPolicy: IfNotPresent

  controller:
    csiProvisioner:
      topology: false

    # nodeSelector:
    #   node-role.kubernetes.io/master: ""
    
    # tolerations:
    #   - key: node-role.kubernetes.io/master
    #     operator: Exists
    #     effect: NoSchedule

  node: {}
    # nodeSelector:
    #   linstor-satellite: ""
    
    # tolerations:
    #   - key: node-role.kubernetes.io/master
    #     operator: Exists
    #     effect: NoSchedule
