{{- $fullName := include "linstor.fullname" . -}}
{{- if .Values.satellite.enabled }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-satellite
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ $fullName }}-satellite
  template:
    metadata:
      labels:
        app: {{ $fullName }}-satellite
    spec:
      {{- if or .Values.satellite.ssl.enabled .Values.satellite.overwriteDrbdConf }}
      initContainers:
      {{- if .Values.satellite.ssl.enabled }}
      - name: load-certs
        image: {{ .Values.satellite.image.repository }}:{{ .Values.satellite.image.tag }}
        imagePullPolicy: {{ .Values.satellite.image.pullPolicy }}
        command:
        - /bin/sh
        - -exc
        - |
          tmp="$(mktemp -u).p12"
          openssl pkcs12 -export -in /tls/satellite/tls.crt -inkey /tls/satellite/tls.key -out "$tmp" -name linstor-satellite -passin 'pass:linstor' -passout 'pass:linstor'
          keytool -importkeystore -srcstorepass linstor -deststorepass linstor -keypass linstor -srckeystore "$tmp" -destkeystore /config/ssl/keystore.jks
          keytool -importcert -noprompt -deststorepass linstor -keypass linstor -file /tls/controller/ca.crt -alias linstor-ca -destkeystore /config/ssl/certificates.jks
          keytool -importcert -noprompt -deststorepass linstor -keypass linstor -file /tls/controller/tls.crt -alias linstor-controller -destkeystore /config/ssl/certificates.jks
          rm -f "$tmp"
        volumeMounts:
        - name: config-ssl
          mountPath: /config/ssl
        - name: controller-tls
          mountPath: /tls/controller
        - name: satellite-tls
          mountPath: /tls/satellite
      {{- end }}
      {{- if .Values.satellite.overwriteDrbdConf }}
      - command:
        - /bin/sh
        - -exc
        - |
          cat /config/drbd.conf > /etc/drbd.conf
          cp -f /config/global_common.conf /etc/drbd.d/global_common.conf
        image: {{ .Values.satellite.image.repository }}:{{ .Values.satellite.image.tag }}
        imagePullPolicy: {{ .Values.satellite.image.pullPolicy }}
        name: load-drbd-conf
        securityContext:
          privileged: true
        volumeMounts:
        - name: config
          mountPath: /config
        - name: etc-drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
        - name: usr-local-sbin
          mountPath: /host-bin
      {{- end }}
      {{- end }}
      containers:
      - name: linstor-satellite
        image: {{ .Values.satellite.image.repository }}:{{ .Values.satellite.image.tag }}
        imagePullPolicy: {{ .Values.satellite.image.pullPolicy }}
        securityContext:
          privileged: true
        volumeMounts:
        {{- if or .Values.satellite.ssl.enabled .Values.satellite.overwriteDrbdConf }}
        - name: config
          mountPath: /config
        {{- end }}
        {{- if .Values.satellite.ssl.enabled }}
        - name: config-ssl
          mountPath: /config/ssl
          readOnly: true
        {{- end }}
        - name: etc-drbd-conf
          mountPath: /etc/drbd.conf
        - name: etc-drbd-d
          mountPath: /etc/drbd.d
        - name: var-lib-drbd
          mountPath: /var/lib/drbd
        - name: var-lib-linstor-d
          mountPath: /var/lib/linstor.d
        - name: lib-modules
          mountPath: /lib/modules
        - name: dev
          mountPath: /dev
        - name: etc-lvm
          mountPath: /etc/lvm
        - name: run-lock-lvm
          mountPath: /run/lock/lvm
        - name: logs
          mountPath: /logs
        - name: run-lvm
          mountPath: /run/lvm
        - name: run-udev
          mountPath: /run/udev
      hostIPC: true
      hostNetwork: true
      hostPID: true
      imagePullSecrets:
        {{- toYaml .Values.satellite.image.pullSecrets | nindent 8 }}
      priorityClassName: system-node-critical
      {{- with .Values.satellite.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.satellite.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - name: etc-drbd-conf
        hostPath:
          path: /etc/drbd.conf
          type: FileOrCreate
      - name: etc-drbd-d
        hostPath:
          path: /etc/drbd.d
      - name: var-lib-drbd
        hostPath:
          path: /var/lib/drbd
      - name: var-lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: usr-local-sbin
        hostPath:
          path: /usr/local/sbin
      - name: dev
        hostPath:
          path: /dev
      - name: etc-lvm
        hostPath:
          path: /etc/lvm
      - name: run-lock-lvm
        hostPath:
          path: /run/lock/lvm
      {{- if or .Values.satellite.ssl.enabled .Values.satellite.overwriteDrbdConf }}
      - name: config
        configMap:
          name: {{ $fullName }}-satellite
      {{- end }}
      {{- if .Values.satellite.ssl.enabled }}
      - name: config-ssl
        emptyDir: {}
      - name: controller-tls
        secret:
          secretName: {{ $fullName }}-controller-tls
      - name: satellite-tls
        secret:
          secretName: {{ $fullName }}-satellite-tls
      {{- end }}
      - name: logs
        hostPath:
          path: /var/log/{{ $fullName }}-satellite
      - name: run-lvm
        hostPath:
          path: /run/lvm
      - name: run-udev
        hostPath:
          path: /run/udev
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.satellite.update.maxUnavailable }}
    type: RollingUpdate
{{- end }}
